EnergyMission_DataManagement/ViewModels/CACViewModel.cs
using Microsoft.AspNetCore.SignalR;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EnergyMission_DataManagement.ViewModels
{
    public class CACViewModel
    {
        public int CAC_id { get; set; }
        [Required]
        public string CAC_number { get; set; }
        public string NMI_number { get; set; }
        public bool UsedForContract { get; set; }
    }
}

EnergyMission_DataManagement/Controllers/AppController.cs
//using AceSchoolPortal.Data;
//using AceSchoolPortal.Data.Entities;
//using AceSchoolPortal.ViewModels;
using EnergyMission_DataManagement.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
//using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace AceSchoolPortal.Controllers
{
    public class AppController : Controller
    {
        private readonly IDataRepository _repository;
        private readonly DataEnergyContext db;

        public AppController(IDataRepository repository, DataEnergyContext db)
        {
            _repository = repository;
            this.db = db;
        }

        public IActionResult index()
        {
            return View();
        }

        public IActionResult Home()
        {
            return View();
        }
        public IActionResult NotEnabled()
        {
            return View();
        }

        public IActionResult NewRegistration()
        {
            return View();
        }
    }
}

EnergyMission_DataManagement/Controllers/CACController.cs
using EnergyMission_DataManagement.Data;
using EnergyMission_DataManagement.Data.Entities;
using EnergyMission_DataManagement.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace AceSchoolPortal.Controllers
{

    public class CACController : Controller
    {
        private readonly IDataRepository _repository;
        private readonly DataEnergyContext db;

        public CACController(IDataRepository repository, DataEnergyContext db)
        {
            _repository = repository;
            this.db = db;
        }

        [Authorize(Roles = "Administrator,SuperAdmin")]
        public IActionResult NewCAC()
        {
            return View();
        }

        
        [HttpGet]
        public IActionResult CACManagement(string searchString)
        {

            var results = _repository.GetAllCACs();

            ViewData["CurrentFilter"] = searchString;
            if (!String.IsNullOrEmpty(searchString))
            {
                results = results.Where(s => s.CAC_number.Contains(searchString));
            }
            return View(results.ToList());
        }

        [Authorize(Roles = "Administrator,SuperAdmin")]
        [HttpPost]
        public IActionResult NewCAC(CACViewModel model)
        {
            var userId = User.FindFirstValue(ClaimTypes.Name);
            if (ModelState.IsValid)
            {
                var newCAC = new CustAccntCode()
                {
                    CAC_number = model.CAC_number,
                    nmi_number = model.NMI_number,
                    UsedForContract = model.UsedForContract,                
                    created_at = DateTime.Now,
                    updated_at = DateTime.Now
                };
                var newOps = new OperationsHistory()
                {
                    nmi_number = model.CAC_number,
                    operation = "Insert",
                    lastupdatedby = userId,
                    created_at = DateTime.Now,
                    updated_at = DateTime.Now
                };
                _repository.AddEntity(newCAC);
                _repository.AddEntity(newOps);
                _repository.SaveAll();
            }
            else
            {
                //show errors
            }

            return RedirectToAction("CACManagement");

        }
        [Authorize(Roles = "Administrator,SuperAdmin")]
        public IActionResult Edit(int id)
        {
            //here, get the user from the database in the real application
            //getting a user from collection for demo purpose
            var usr = _repository.GetAllCACs().Where(s => s.CAC_id == id).FirstOrDefault();
            return View(usr);
        }

        [HttpPost]
        public IActionResult Edit(CustAccntCode cac)
        {
            //update nmi in DB using EntityFramework in real-life application
            //update list by removing old user and adding updated user for demo purpose
            var resultcac = _repository.GetAllCACs().Where(s => s.CAC_id == cac.CAC_id).FirstOrDefault();

            // created date should remain the same
            cac.created_at = resultcac.created_at;
            //// edited/updated date should be updated to current date (date of the edit)
            cac.updated_at = DateTime.Now;
            //// This will look for the current user claim ( current logged in user )
            var userId = User.FindFirstValue(ClaimTypes.Name);
            cac.lastupdatedby = userId;
            var newOps = new OperationsHistory()
            {
                cac_number = cac.CAC_number,
                operation = "Updated",
                lastupdatedby = userId,
                created_at = DateTime.Now,
                updated_at = DateTime.Now
            };

            _repository.RemoveEntity(resultcac);
            _repository.AddEntity(cac);
            _repository.AddEntity(newOps);
            _repository.SaveAll();

            return RedirectToAction("CACManagement");
        }

        [Authorize(Roles = "SuperAdmin")]
        public IActionResult Delete(int id)
        {
            //here, get the student from the database in the real application
            //getting a student from collection for demo purpose
            var sub = _repository.GetAllCACs().Where(s => s.CAC_id == id).FirstOrDefault();
            return View(sub);
        }

        [HttpPost]
        public ActionResult Delete(CustAccntCode cac)
        {
            //update student in DB using EntityFramework in real-life application

            //update list by removing old student and adding updated student for demo purpose
            var resultcac = _repository.GetAllCACs().Where(s => s.CAC_id == cac.CAC_id).FirstOrDefault();
            var userId = User.FindFirstValue(ClaimTypes.Name);

            var newOps = new OperationsHistory()
            {
                cac_number = cac.CAC_number,
                operation = "Delete",
                lastupdatedby = userId,
                created_at = DateTime.Now,
                updated_at = DateTime.Now
            };

            _repository.RemoveEntity(resultcac);
            _repository.AddEntity(newOps);
            _repository.SaveAll();

            return RedirectToAction("CACManagement");
        }


    }
}

EnergyMission_DataManagement/Views/CAC/CACManagement.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<CustAccntCode>
<center><h2>CAC Management</h2></center>
<a asp-controller="App" asp-action="Home"> &lt; Go Back</a>
<br />
<br />
<p>CAC Count: @Model.Count()</p>
<button class="btn btn-dark"><a asp-controller="CAC" asp-action="NewCAC" class="nav-link" style="color:aqua">Add CAC</a></button>
<br />
<br />
<div>
    <center>
        <form asp-action="CACManagement" method="get">
            <div class="form-actions no-color">
                <p>
                    Search by <b>Contract ID</b> or <b>NMI</b> or <b>Order Number</b>: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
                    <input type="submit" value="Search" class="btn btn-info" /> |
                    <a asp-action="CACManagement">Back to Full List</a>
                </p>
            </div>
        </form>
        <table class="table table-striped table-bordered" style="margin-left:30px;margin-right:30px; margin-left:30px">
            <thead class="thead-dark">
                <tr>
                    <th> Customer Account Code (CAC) </th>
                    <th> NMI (National Meter Identifier) </th>
                    <th> Used For Contract </th>
                    <th style="color:darkcyan"> Update </th>
                    <th style="color:darkcyan"> Delete </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var p in Model)
                {
                <tr>
                    <td>  @p.CAC_number </td>
                    <td>  @p.nmi_number </td>
                    <td>  @p.UsedForContract </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = p.CAC_id })
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", new { id = p.CAC_id })
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </center>
</div>

EnergyMission_DataManagement/Views/CAC/Delete.cshtml
@model CustAccntCode
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete CAC</h2>

@using (Html.BeginForm())
{

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CAC_id)

        <div class="form-group">
            @Html.LabelFor(model => model.CAC_number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CAC_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CAC_number, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "NMIManagement")
</div>

EnergyMission_DataManagement/Views/CAC/Edit.cshtml
@model CustAccntCode
@{
    ViewBag.Title = "Edit";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit CAC</h2>

@using (Html.BeginForm())
{
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.CAC_number)

    <div class="form-group">
        <b> @Html.Label("Customer Account Code :")</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.CAC_number, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CAC_number, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b> @Html.Label("National Meter Identifier :")</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.nmi_number, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nmi_number, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "CACManagement")
</div>

EnergyMission_DataManagement/Views/CAC/NewCAC.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model CACViewModel
@{
    ViewBag.Title = "New CAC Page";
}
@section Scripts {
    <script src="~/lib/jquery/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.validate.unobtrusive.min.js"></script>
}

<div class="col-md-6 offset-md-3">
    <div class="card card-body">
        <form method="post">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <div class="col-md-4 col-lg-6 col-xs-12">
                    <label asp-for="CAC_number">CAC ID:</label>
                    <input asp-for="CAC_number" type="text" class="form-control">
                    <span asp-validation-for="CAC_number"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4 col-lg-6 col-xs-12">
                    <label asp-for="NMI_number">NMI:</label>
                    <input asp-for="NMI_number" type="text" class="form-control">
                    <span asp-validation-for="NMI_number"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4 col-lg-6 col-xs-12">
                    <label asp-for="UsedForContract">Used For Contract:</label>
                    <input asp-for="UsedForContract" type="checkbox" class="form-control">
                    <span asp-validation-for="UsedForContract"></span>
                </div>
            </div>
            <br>
            <div class="col-md-12 col-lg-12 col-xs-12">
                <button type="submit" class="btn btn-warning">Submit</button>
                <div>@ViewBag.UserMessage</div>
            </div>
        </form>
    </div>