EnergyMission_DataManagement/ViewModels/ContractViewModel.cs
using Microsoft.AspNetCore.SignalR;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EnergyMission_DataManagement.ViewModels
{
    public class NewContractViewModel
    {
        public int Contract_id { get; set; }
        [Required]
        public string Contract_number { get; set; }
        public string NMI_number { get; set; }
        public string OrderNumber { get; set; }
        public DateTime StartOfDeliveryDate { get; set; }
        public string PaymentReferenceNumber { get; set; }
        public string Jusridiction { get; set; }
        public string Distributor { get; set; }
        public string MeterType { get; set; }
        public string MeterSerialNumber { get; set; }
        public string MeterReads { get; set; }
    }
}

EnergyMission_DataManagement/Controllers/AppController.cs
//using AceSchoolPortal.Data;
//using AceSchoolPortal.Data.Entities;
//using AceSchoolPortal.ViewModels;
using EnergyMission_DataManagement.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
//using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace AceSchoolPortal.Controllers
{
    public class AppController : Controller
    {
        private readonly IDataRepository _repository;
        private readonly DataEnergyContext db;

        public AppController(IDataRepository repository, DataEnergyContext db)
        {
            _repository = repository;
            this.db = db;
        }

        public IActionResult index()
        {
            return View();
        }

        public IActionResult Home()
        {
            return View();
        }
        public IActionResult NotEnabled()
        {
            return View();
        }

        public IActionResult NewRegistration()
        {
            return View();
        }
    }
}

EnergyMission_DataManagement/Controllers/ContractController.cs
using EnergyMission_DataManagement.Data;
using EnergyMission_DataManagement.Data.Entities;
using EnergyMission_DataManagement.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace AceSchoolPortal.Controllers
{
    public class ContractController : Controller
    {
        private readonly IDataRepository _repository;
        private readonly DataEnergyContext db;

        public ContractController(IDataRepository repository, DataEnergyContext db)
        {
            _repository = repository;
            this.db = db;
        }

        [Authorize(Roles = "Administrator,SuperAdmin")]
        public IActionResult NewContract()
        {
            return View();
        }

        public IActionResult ContractManagement(string searchString)
        {

            var results = _repository.GetAllContracts();

            ViewData["CurrentFilter"] = searchString;
            if (!String.IsNullOrEmpty(searchString))
            {
                results = results.Where(s => s.contract_number.Contains(searchString)
                                           || s.nmi_number.Contains(searchString)
                                           || s.jurisdiction.Contains(searchString)
                                           || s.metertype.Contains(searchString)
                                           /*|| s.ordernumber.Contains(searchString)*/);
            }
            return View(results.ToList());
        }

        [HttpPost]
        public IActionResult NewContract(NewContractViewModel model)
        {
            var userId = User.FindFirstValue(ClaimTypes.Name);
            if (ModelState.IsValid)
            {
                var newContract = new Contract()
                {
                    contract_number = model.Contract_number,
                    nmi_number = model.NMI_number,
                    jurisdiction = model.Jusridiction,
                    distributor = model.Distributor,
                    metertype = model.MeterType,
                    startofdelivery = model.StartOfDeliveryDate,
                    ordernumber = model.OrderNumber,
                    paymentreferencenumber = model.PaymentReferenceNumber,
                    meterserialno = model.MeterSerialNumber,
                    lastupdatedby = userId,
                    created_at = DateTime.Now,
                    updated_at = DateTime.Now
                };

                var newOps = new OperationsHistory()
                {
                    nmi_number = model.Contract_number,
                    operation = "Insert",
                    lastupdatedby = userId,
                    created_at = DateTime.Now,
                    updated_at = DateTime.Now
                };

                _repository.AddEntity(newContract);
                _repository.AddEntity(newOps);
                _repository.SaveAll();
                   
            }
            else
            {
                //show errors
            }

            return RedirectToAction("ContractManagement");

        }

        [Authorize(Roles = "Administrator,SuperAdmin")]
        public IActionResult Edit(int id)
        {
            //here, get the user from the database in the real application
            //getting a user from collection for demo purpose
            var usr = _repository.GetAllContracts().Where(s => s.contract_id == id).FirstOrDefault();
            return View(usr);
        }

        [HttpPost]
        public IActionResult Edit(Contract contract)
        {
            //update nmi in DB using EntityFramework in real-life application
            //update list by removing old user and adding updated user for demo purpose
            var resultcontract = _repository.GetAllContracts().Where(s => s.contract_id == contract.contract_id).FirstOrDefault();

            // created date should remain the same
            contract.created_at = resultcontract.created_at;
            // edited/updated date should be updated to current date (date of the edit)
            contract.updated_at = DateTime.Now;
            // This will look for the current user claim ( current logged in user )
            var userId = User.FindFirstValue(ClaimTypes.Name);
            contract.lastupdatedby = userId;
            var newOps = new OperationsHistory()
            {
                contract_number = contract.contract_number,
                operation = "Updated",
                lastupdatedby = userId,
                created_at = DateTime.Now,
                updated_at = DateTime.Now
            };


            _repository.RemoveEntity(resultcontract);
            _repository.AddEntity(contract);
            _repository.AddEntity(newOps);
            _repository.SaveAll();

            return RedirectToAction("ContractManagement");
        }

        [Authorize(Roles = "SuperAdmin")]
        public IActionResult Delete(int id)
        {
            //here, get the student from the database in the real application
            //getting a student from collection for demo purpose
            var sub = _repository.GetAllContracts().Where(s => s.contract_id == id).FirstOrDefault();
            return View(sub);
        }

        [HttpPost]
        public ActionResult Delete(Contract contract)
        {
            //update student in DB using EntityFramework in real-life application

            //update list by removing old student and adding updated student for demo purpose
            var resultcontract = _repository.GetAllContracts().Where(s => s.contract_id == contract.contract_id).FirstOrDefault();
            var userId = User.FindFirstValue(ClaimTypes.Name);

            var newOps = new OperationsHistory()
            {
                nmi_number = contract.nmi_number,
                operation = "Delete",
                lastupdatedby = userId,
                created_at = DateTime.Now,
                updated_at = DateTime.Now
            };

            _repository.RemoveEntity(resultcontract);
            _repository.AddEntity(newOps);
            _repository.SaveAll();

            return RedirectToAction("ContractManagement");
        }

    }
}

EnergyMission_DataManagement/Views/Contract/ContractManagement.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<Contract>
<center><h2>Contract Management</h2></center>
<a asp-controller="App" asp-action="Home"> &lt; Go Back</a>
<br />
<br />
<p>Contract Count: @Model.Count()</p>
<button class="btn btn-dark"><a asp-controller="Contract" asp-action="NewContract" class="nav-link" style="color:aqua">Add Contract</a></button>
<br />
<br />
<div>
    <center>
        <form asp-action="ContractManagement" method="get">
            <div class="form-actions no-color">
                <p>
                    Search by <b>Contract ID</b> or <b>NMI</b> or <b>Order Number</b> or <b>Jurisdiction</b> or <b>Meter Type</b>: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
                    <input type="submit" value="Search" class="btn btn-info" /> |
                    <a asp-action="ContractManagement">Back to Full List</a>
                </p>
            </div>
        </form>
        <table class="table table-striped table-bordered center">
            <thead class="thead-dark">
                <tr>
                    <th> Contract ID </th>
                    <th> NMI (National Meter Identifier) </th>
                    <th> Order Number </th>
                    <th> PRN (Payment Reference Number) </th>
                    <th> Jurisdiction </th>
                    <th> Meter Type </th>
                    <th> Meter Serial Number </th>
                    <th> Last Updated by</th>
                    <th> Created on/at </th>
                    <th> Updated on/at </th>
                    <th style="color:darkcyan"> Update </th>
                    <th style="color:darkcyan"> Delete </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var p in Model)
                {
                <tr>
                    <td>  @p.contract_number </td>
                    <td>  @p.nmi_number</td>
                    <td>  @p.ordernumber </td>
                    <td>  @p.paymentreferencenumber </td>
                    <td>  @p.jurisdiction </td>
                    <td>  @p.metertype </td>
                    <td>  @p.meterserialno </td>
                    <td>  @p.lastupdatedby </td>
                    <td>  @p.created_at </td>
                    <td>  @p.updated_at</td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = p.contract_id })
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", new { id = p.contract_id })
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </center>
</div>

EnergyMission_DataManagement/Views/Contract/Delete.cshtml
@model Contract
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete NMI</h2>

@using (Html.BeginForm())
{

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.contract_id)

        <div class="form-group">
            @Html.LabelFor(model => model.contract_number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contract_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contract_number, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ContractManagement")
</div>

EnergyMission_DataManagement/Views/Contract/Edit.cshtml
@model Contract
@{
    ViewBag.Title = "Edit";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Contract</h2>

@using (Html.BeginForm())
{
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.contract_id)

<div class="form-group">
    <b>  @Html.Label("Contract Number:") </b>
    <div class="col-md-10">
        @Html.EditorFor(model => model.contract_number, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.contract_number, "", new { @class = "text-danger" })
    </div>
</div>

    <div class="form-group">
        <b>  @Html.Label("NMI Number:") </b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.nmi_number, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nmi_number, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b>  @Html.Label("Jurisdiction:") </b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.jurisdiction, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.jurisdiction, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b>  @Html.Label("Meter Type") </b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.metertype, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.metertype, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b>  @Html.Label("Order Number") </b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.ordernumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ordernumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b>  @Html.Label("Payment Reference Number") </b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.paymentreferencenumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.paymentreferencenumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-info" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "ContractManagement")
</div>

EnergyMission_DataManagement/Views/Contract/NewContract.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model NewContractViewModel
@{
    ViewBag.Title = "New Contract Page";
}
@section Scripts {
    <script src="~/lib/jquery/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.validate.unobtrusive.min.js"></script>
}

<div class="col-md-6 offset-md-3">
    <div class="card card-body">
        <form method="post">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <div class="col-md-4 col-lg-6 col-xs-12">
                    <label asp-for="Contract_number">Contract ID:</label>
                    <input asp-for="Contract_number" type="text" class="form-control">
                    <span asp-validation-for="Contract_number"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4 col-lg-6 col-xs-12">
                    <label asp-for="NMI_number">NMI:</label>
                    <input asp-for="NMI_number" type="text" class="form-control">
                    <span asp-validation-for="NMI_number"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4 col-lg-6 col-xs-12">
                    <label asp-for="Jusridiction">Jusrisdiction:</label>
                    <input asp-for="Jusridiction" type="text" class="form-control">
                    <span asp-validation-for="Jusridiction"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4 col-lg-6 col-xs-12">
                    <label asp-for="Distributor">Distributor:</label>
                    <input asp-for="Distributor" type="text" class="form-control">
                    <span asp-validation-for="Distributor"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4 col-lg-6 col-xs-12">
                    <label asp-for="MeterType">Meter Type:</label>
                    <input asp-for="MeterType" type="text" class="form-control">
                    <span asp-validation-for="MeterType"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4 col-lg-6 col-xs-12">
                    <label asp-for="OrderNumber">OrderNumber:</label>
                    <input asp-for="OrderNumber" type="text" class="form-control">
                    <span asp-validation-for="OrderNumber"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4 col-lg-6 col-xs-12">
                    <label asp-for="StartOfDeliveryDate">Start of Delivery:</label>
                    <input asp-for="StartOfDeliveryDate" type="date" asp-format="{0:yyyy-MM-dd}" class="form-control">
                    <span asp-validation-for="StartOfDeliveryDate"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4 col-lg-6 col-xs-12">
                    <label asp-for="PaymentReferenceNumber">Payment Reference Number:</label>
                    <input asp-for="PaymentReferenceNumber" type="text" class="form-control">
                    <span asp-validation-for="PaymentReferenceNumber"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4 col-lg-6 col-xs-12">
                    <label asp-for="MeterSerialNumber">Meter Serial Number:</label>
                    <input asp-for="MeterSerialNumber" type="text" class="form-control">
                    <span asp-validation-for="MeterSerialNumber"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4 col-lg-6 col-xs-12">
                    <label asp-for="MeterReads">Meter Reads:</label>
                    <input asp-for="MeterReads" type="text" class="form-control">
                    <span asp-validation-for="MeterReads"></span>
                </div>
            </div>
            <br>
            <div class="col-md-12 col-lg-12 col-xs-12">
                <button type="submit" class="btn btn-warning">Submit</button>
                <div>@ViewBag.UserMessage</div>
            </div>
        </form>
    </div>